from typing import Protocol, Optional

class IAttemptRepo(Protocol):
    async def add(self, attempt: dict) -> None: ...
    async def get(self, attempt_id: str) -> Optional[dict]: ...
    async def list(self, task_id: Optional[str]=None, user_id: Optional[str]=None, limit: int = 50, offset: int = 0): ...
    async def list_by_user(self, user_id: str): ...
