from typing import Protocol, Sequence, Dict, Any
class ILLM(Protocol):
    async def check_solution(self, task: str, user_solution: str) -> Dict[str, Any]: ...
    async def hint(self, task: str, chat_history: Sequence[Dict[str, str]]) -> str: ...
    async def solve(self, task: str) -> str: ...
    async def image_to_text_bytes(self, image_bytes: bytes, mime: str = "image/png") -> str: ...
